# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pynq.remote import dma_pb2 as dma__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dma_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class DmaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.bind_dma = channel.unary_unary(
                '/dma.Dma/bind_dma',
                request_serializer=dma__pb2.BindDmaRequest.SerializeToString,
                response_deserializer=dma__pb2.BindDmaResponse.FromString,
                _registered_method=True)
        self.transfer = channel.unary_unary(
                '/dma.Dma/transfer',
                request_serializer=dma__pb2.TransferRequest.SerializeToString,
                response_deserializer=dma__pb2.TransferResponse.FromString,
                _registered_method=True)
        self.wait = channel.unary_unary(
                '/dma.Dma/wait',
                request_serializer=dma__pb2.WaitRequest.SerializeToString,
                response_deserializer=dma__pb2.WaitResponse.FromString,
                _registered_method=True)
        self.stop = channel.unary_unary(
                '/dma.Dma/stop',
                request_serializer=dma__pb2.StopRequest.SerializeToString,
                response_deserializer=dma__pb2.StopResponse.FromString,
                _registered_method=True)
        self.status = channel.unary_unary(
                '/dma.Dma/status',
                request_serializer=dma__pb2.StatusRequest.SerializeToString,
                response_deserializer=dma__pb2.StatusResponse.FromString,
                _registered_method=True)


class DmaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def bind_dma(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def transfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def wait(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DmaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'bind_dma': grpc.unary_unary_rpc_method_handler(
                    servicer.bind_dma,
                    request_deserializer=dma__pb2.BindDmaRequest.FromString,
                    response_serializer=dma__pb2.BindDmaResponse.SerializeToString,
            ),
            'transfer': grpc.unary_unary_rpc_method_handler(
                    servicer.transfer,
                    request_deserializer=dma__pb2.TransferRequest.FromString,
                    response_serializer=dma__pb2.TransferResponse.SerializeToString,
            ),
            'wait': grpc.unary_unary_rpc_method_handler(
                    servicer.wait,
                    request_deserializer=dma__pb2.WaitRequest.FromString,
                    response_serializer=dma__pb2.WaitResponse.SerializeToString,
            ),
            'stop': grpc.unary_unary_rpc_method_handler(
                    servicer.stop,
                    request_deserializer=dma__pb2.StopRequest.FromString,
                    response_serializer=dma__pb2.StopResponse.SerializeToString,
            ),
            'status': grpc.unary_unary_rpc_method_handler(
                    servicer.status,
                    request_deserializer=dma__pb2.StatusRequest.FromString,
                    response_serializer=dma__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dma.Dma', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dma.Dma', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Dma(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def bind_dma(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dma.Dma/bind_dma',
            dma__pb2.BindDmaRequest.SerializeToString,
            dma__pb2.BindDmaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def transfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dma.Dma/transfer',
            dma__pb2.TransferRequest.SerializeToString,
            dma__pb2.TransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def wait(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dma.Dma/wait',
            dma__pb2.WaitRequest.SerializeToString,
            dma__pb2.WaitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dma.Dma/stop',
            dma__pb2.StopRequest.SerializeToString,
            dma__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dma.Dma/status',
            dma__pb2.StatusRequest.SerializeToString,
            dma__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
